---
- name: create dir
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  loop:
    - /opt/postgres/dump
    - /opt/postgres/data

- name: copy docker-compose
  copy:
    src: "{{ item }}"
    dest: /opt/postgres/
    owner: root
    mode: 766
  loop: "{{ compose }}"

- name: Check if Docker service is running
  command: systemctl is-active docker
  register: docker_service_status
  ignore_errors: true

- name: Install Docker if not running
  include_role:
    name: docker-onl
  when: docker_service_status.rc != 0

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: /opt/postgres/
    files:
    - docker-compose.yml
  register: output