version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      # - ../2. Init Database:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
      - ./dump:/tmp
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - eisk

  pgadmin:
    container_name: pgadmin
    image: elestio/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 80:80
    # volumes:
    #   - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - eisk

networks:
  eisk: